# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Podproxy < Formula
  desc "Kubernetes pod proxy that routes traffic through pod port-forwarding"
  homepage "https://github.com/entwico/podproxy"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/entwico/podproxy/releases/download/v1.2.0/podproxy_darwin_amd64.tar.gz"
      sha256 "2b18ee6028d7711888dc8f17c5b4709ff41891b9154b82d06b506fca225b84db"

      define_method(:install) do
        bin.install "podproxy"
        (etc/"podproxy").install "defaults.yaml" => "config.yaml" unless (etc/"podproxy/config.yaml").exist?
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/entwico/podproxy/releases/download/v1.2.0/podproxy_darwin_arm64.tar.gz"
      sha256 "31ba9428ef65e74e5b23339d269a86a59821445a53d2c95799ad952ef2a98a53"

      define_method(:install) do
        bin.install "podproxy"
        (etc/"podproxy").install "defaults.yaml" => "config.yaml" unless (etc/"podproxy/config.yaml").exist?
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/entwico/podproxy/releases/download/v1.2.0/podproxy_linux_amd64.tar.gz"
      sha256 "3c6adc994134d37afdd108174ce6be9364931d4bd98dd11cb076e3f75537404b"
      define_method(:install) do
        bin.install "podproxy"
        (etc/"podproxy").install "defaults.yaml" => "config.yaml" unless (etc/"podproxy/config.yaml").exist?
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/entwico/podproxy/releases/download/v1.2.0/podproxy_linux_arm64.tar.gz"
      sha256 "e877029ad158b9e409097586d3b02c997eaca2da6b4aa15c2fe60bbcae68537e"
      define_method(:install) do
        bin.install "podproxy"
        (etc/"podproxy").install "defaults.yaml" => "config.yaml" unless (etc/"podproxy/config.yaml").exist?
      end
    end
  end

  def caveats
    <<~EOS
      Configuration file:
        #{etc}/podproxy/config.yaml

      A default config is installed if one does not already exist.
      Edit it before starting the service:
        $EDITOR #{etc}/podproxy/config.yaml

      To start podproxy as a background service:
        brew services start #{name}

      To stop the service:
        brew services stop #{name}

      Logs are written to:
        #{var}/log/podproxy.log
    EOS
  end

  service do
    run [opt_bin/"podproxy", "--config", etc/"podproxy/config.yaml"]
    keep_alive true
    log_path var/"log/podproxy.log"
    error_log_path var/"log/podproxy.log"
    working_dir var
  end
end
