# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Podproxy < Formula
  desc "Kubernetes pod proxy that routes traffic through pod port-forwarding"
  homepage "https://github.com/entwico/podproxy"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/entwico/podproxy/releases/download/v1.3.0/podproxy_darwin_amd64.tar.gz"
      sha256 "847cc93e9c519943aa82d6a25a7517b3315b0c77b0c5401a00b4f990fa879b47"

      def install
        bin.install "podproxy"
        (etc/"podproxy").install "defaults.yaml" => "config.yaml" unless (etc/"podproxy/config.yaml").exist?
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/entwico/podproxy/releases/download/v1.3.0/podproxy_darwin_arm64.tar.gz"
      sha256 "7b2a8c839becefc1fa9b97788adcc7257d0bee23e5bac6d6c631a19e69ad7d12"

      def install
        bin.install "podproxy"
        (etc/"podproxy").install "defaults.yaml" => "config.yaml" unless (etc/"podproxy/config.yaml").exist?
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/entwico/podproxy/releases/download/v1.3.0/podproxy_linux_amd64.tar.gz"
      sha256 "93d3852845f13796ed16ec2ec19dd5d55867494c951c4bc7efed2f130326a459"
      def install
        bin.install "podproxy"
        (etc/"podproxy").install "defaults.yaml" => "config.yaml" unless (etc/"podproxy/config.yaml").exist?
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/entwico/podproxy/releases/download/v1.3.0/podproxy_linux_arm64.tar.gz"
      sha256 "c5644b5a67c7718b1fb75b38c386225f4ea9b39c6a965157e6045683c910516c"
      def install
        bin.install "podproxy"
        (etc/"podproxy").install "defaults.yaml" => "config.yaml" unless (etc/"podproxy/config.yaml").exist?
      end
    end
  end

  def caveats
    <<~EOS
      Configuration file:
        #{etc}/podproxy/config.yaml

      A default config is installed if one does not already exist.
      Edit it before starting the service:
        $EDITOR #{etc}/podproxy/config.yaml

      To start podproxy as a background service:
        brew services start #{name}

      To stop the service:
        brew services stop #{name}

      Logs are written to:
        #{var}/log/podproxy.log
    EOS
  end

  service do
    run [opt_bin/"podproxy", "--config", etc/"podproxy/config.yaml"]
    keep_alive true
    log_path var/"log/podproxy.log"
    error_log_path var/"log/podproxy.log"
    working_dir var
  end
end
