# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Podproxy < Formula
  desc "Kubernetes pod proxy that routes traffic through pod port-forwarding"
  homepage "https://github.com/entwico/podproxy"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/entwico/podproxy/releases/download/v1.1.0/podproxy_darwin_amd64.tar.gz"
      sha256 "a227c7aa5161ebf2e8a494754fe9d626df15917004d433030e25e1f8daf7266b"

      define_method(:install) do
        bin.install "podproxy"
        (etc/"podproxy").install "defaults.yaml" => "config.yaml" unless (etc/"podproxy/config.yaml").exist?
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/entwico/podproxy/releases/download/v1.1.0/podproxy_darwin_arm64.tar.gz"
      sha256 "5f0c59bfe615e871dca7f6fa8660fcd12a03e4a41c05df0a118da31951a73dfd"

      define_method(:install) do
        bin.install "podproxy"
        (etc/"podproxy").install "defaults.yaml" => "config.yaml" unless (etc/"podproxy/config.yaml").exist?
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/entwico/podproxy/releases/download/v1.1.0/podproxy_linux_amd64.tar.gz"
      sha256 "6b3c3729044941c8c46ee7480bb4b41576fdea8beda6078cedd031fc6cc5a846"
      define_method(:install) do
        bin.install "podproxy"
        (etc/"podproxy").install "defaults.yaml" => "config.yaml" unless (etc/"podproxy/config.yaml").exist?
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/entwico/podproxy/releases/download/v1.1.0/podproxy_linux_arm64.tar.gz"
      sha256 "78ec52e8e2074b6cd7037158bad136244edee0808acd6ca2d53ed532d8acbbb5"
      define_method(:install) do
        bin.install "podproxy"
        (etc/"podproxy").install "defaults.yaml" => "config.yaml" unless (etc/"podproxy/config.yaml").exist?
      end
    end
  end

  def caveats
    <<~EOS
      Configuration file:
        #{etc}/podproxy/config.yaml

      A default config is installed if one does not already exist.
      Edit it before starting the service:
        $EDITOR #{etc}/podproxy/config.yaml

      To start podproxy as a background service:
        brew services start #{name}

      To stop the service:
        brew services stop #{name}

      Logs are written to:
        #{var}/log/podproxy.log
    EOS
  end

  service do
    run [opt_bin/"podproxy", "--config", etc/"podproxy/config.yaml"]
    keep_alive true
    log_path var/"log/podproxy.log"
    error_log_path var/"log/podproxy.log"
    working_dir var
  end
end
